# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use
# For example: application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# https://docs.spring.io/spring-boot/reference/features/profiles.html
# ===================================================================

logging:
  level:
    root: info
    com.dct.base: info
    org.springframework.security: info
    org.hibernate.sql: info
  charset:
    console: UTF-8
    file: UTF-8
  # Custom properties to define logs file paths according to different profiles
  file-path: /mnt/logs

spring:
  sql:
    init:
      mode: never
  jpa:
    # Avoid causing LazyInitializationException if querying outside the scope of EntityManager or causing poor performance
    open-in-view: false
    hibernate:
      # Hibernate only checks if the current schema matches the entity
      # If it does not match, the application will not start
      # Do not make any changes to the schema
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        jdbc:
          time_zone: UTC
          ddl-auto: validate
  jackson:
    time-zone: UTC
  servlet:
    multipart:
      enabled: true
      # Maximum size of the entire HTTP request when uploading multipart data (including files and other parameters)
      max-request-size: 50MB
      # Maximum size for each file that a user can upload
      max-file-size: 10MB

dct:
  base:
    security:
      auth:
        enabled-tls: true
        base64-secret-key: ${DCT_STARTER_SECRET_KEY}
        # Token is valid default in 1 hour and 7 days for remember me
        token-validity: 3600000 # milliseconds
        token-validity-for-remember-me: 604800000 # milliseconds
