# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use
# For example: application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# https://docs.spring.io/spring-boot/reference/features/profiles.html
# ===================================================================

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging:
  level:
    root: debug
    com.dct.base: debug
    org.springframework.security: debug
  charset:
    console: UTF-8
    file: UTF-8
  # Custom properties to define logs file paths according to different profiles
  file-path: mnt/logs

dct:
  base:
    domain: http://localhost:${server.port}
    socket:
      enabled: false
    security:
      auth:
        enabled-tls: false
        base64-secret-key: ZGN0LWJhc2Utc2VjcmV0LWtleS10b2tlbi12YWxpZGl0eS04NjQwMDAwMG1zLWZvci1yZW1lbWJlci1tZS04NjQwMDAwMG1z
        # Token is valid default in 1 hour and 7 days for remember me
        token-validity: 3600000 # milliseconds
        token-validity-for-remember-me: 604800000 # milliseconds
      oauth2:
        enabled: false
        base-authorize-uri: /api/p/v1/auth/oauth2/authorize # Add /{registrationId} (eg: /google) when calling from clients
        clients:
          - provider: google
            client-name: Demo Starter Google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - https://www.googleapis.com/auth/userinfo.email
              - https://www.googleapis.com/auth/userinfo.profile
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            redirect-uri: ${dct.base.domain}/login/oauth2/code/google
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            username-attribute-name: sub

          - provider: facebook
            client-name: Demo Starter Facebook
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope:
              - email
              - public_profile
            authorization-uri: https://www.facebook.com/v13.0/dialog/oauth
            redirect-uri: ${dct.base.domain}/login/oauth2/code/facebook
            token-uri: https://graph.facebook.com/v13.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
            username-attribute-name: id
